---
# Source: microservice2/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: microservice2
  labels:
    app: microservice2
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: microservice2
---
# Source: microservice2/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice2
  labels:
    app: microservice2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice2
  template:
    metadata:
      labels:
        app: microservice2
    spec:
      containers:
      - name: microservice2
        image: nginx:1.16.0
        ports:
        - containerPort: 80
