resources:
  - ../../../base/microservice2
  - route.yaml
  - namespace.yaml
patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: microservice2
  - path: patch-service.yaml
    target:
      kind: Service
      name: microservice2
