apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: microservice1
  namespace: dev-namespace
spec:
  to:
    kind: Service
    name: microservice1
  host: microservice1-dev.dev.apps.ocp4.example.com
  port:
    targetPort: 80
