---
# Source: microservice1/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice1-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Custom Nginx Page</title>
    </head>
    <body>
      <h1>Welcome to My Custom Nginx Page!</h1>
    </body>
    </html>
---
# Source: microservice1/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: microservice1
  labels:
    app: microservice1
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: microservice1
---
# Source: microservice1/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1
  labels:
    app: microservice1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      serviceAccountName: microservice1-sa
      containers:
      - name: microservice1
        image: nginx:1.27.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: microservice1-html
