apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "testme.fullname" . }}
  labels:
    {{- include "testme.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "testme.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "testme.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.name }}-sa
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: {{ .Values.name }}-html
